#!/bin/bash
# print a table of selected distances and angles from an XYZ trajectory

from AaronTools.geometry import Geometry
from AaronTools.fileIO import FileReader
import numpy as np

fr = FileReader('molecules.xyz', get_all=True)

geom_list = []
step = 0
print("Step   R(1,2)  A(2,1,3)")
for struc in fr.all_geom:
    geom = Geometry(struc["atoms"])
    # get atoms 1, 2, 3
    a1, a2, a3 = geom.find(['1','2','3'])
    dist = a1.dist(a2)
    angle = np.degrees(geom.angle(a2, a1, a3))
    print(step, dist, angle)
    step += 1
