#!/bin/bash
# scan over x, z coordinates for benzene dimer and calculate wB97X-D/def2-TZVP single point for each
# assumes there is a local file called 'benzene.xyz' containing benzene coordinates in xy-plane

for x in `seq 0 0.5 5`; do
	for z in `seq 3 0.2 4`; do
		name=x.$x.z.$z
		combineMonomers.py benzene.xyz benzene.xyz | translate.py -v $x 0 $z -t 13-24 | makeInput.py -m wb97xd -b def2tzvp -o $name.com
  		jobSubmit.py $name.com -p 8 -m 12
	done
done
