#!/bin/bash
# Perform wB97XD/def2TZVP optimizations/frequencies on all XYZ files 

for XYZ in `/bin/ls *.xyz`; do
    name=`basename $XYZ .xyz`  # get filename without .xyz
    makeInput.py $XYZ -m wB97XD -b "def2tzvp" -opt -freq -o $name.com -np 8 -mem 12
    jobSubmit.py $name.com -p 8 -m 12
done
