#!/bin/bash
# Perform wB97XD/def2TZVP optimizations/frequencies on all molecules listed in 'molecules'

for mol in `cat molecules`; do
    safe_name=`echo $mol | tr -dc [:alnum:]` # strip non alphanumeric characters from name
    fetchMolecule.py -i "$mol" | makeInput.py -m wB97XD -b "def2tzvp" -opt -freq -o $safe_name.com -np 8 -mem 12
    jobSubmit.py $safe_name.com -p 8 -m 12
done
