# Required
version: 2
# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
  commands:
    - mkdir --parents _readtehdocs/html/
    - cp --recursive build/html/* _readthedocs/html/

      #sphinx:
      #   configuration: source/conf.py
      #
      #python:
      #   install:
      #   - requirements: requirements.txt


